steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'europe-west1-docker.pkg.dev/project-e5e0244c-b94d-41a1-810/gazzetta-docker/gazzetta-agents:latest'
    - '-f'
    - 'Dockerfile.agents'
    - '.'
images:
- 'europe-west1-docker.pkg.dev/project-e5e0244c-b94d-41a1-810/gazzetta-docker/gazzetta-agents:latest'
