#!/usr/bin/env python3
"""phase3_daily_brief.py — Generate daily capital flows brief from scored candidates.

Input:  data/phase2_scores.json
Output: data/phase3_daily_brief.md
"""

import json
import os
from datetime import datetime, timezone

PROJECT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(PROJECT, "data")


def load_scores():
    scores_path = os.path.join(DATA, "phase2_scores.json")
    if os.path.exists(scores_path):
        with open(scores_path) as f:
            return json.load(f)

    # Fallback: generate from flows
    flows_path = os.path.join(DATA, "flows.json")
    if os.path.exists(flows_path):
        with open(flows_path) as f:
            flows = json.load(f)
            candidates = []
            for flow in flows.get("flows", []):
                candidates.append({
                    "id": flow.get("id", ""),
                    "title": flow.get("headline", ""),
                    "hook_strength": min(10, flow.get("confidence_pct", 50) // 10),
                    "actionability": 7,
                    "contradiction": 5,
                    "credibility": 8,
                    "total_score": flow.get("confidence_pct", 50),
                })
            return {
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "total_scored": len(candidates),
                "top_score": max((c["total_score"] for c in candidates), default=0),
                "candidates": candidates,
            }

    return {"candidates": []}


def main():
    scores = load_scores()
    candidates = scores.get("candidates", [])
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    if not candidates:
        brief = f"""# Gazzetta di Kyiv — Daily Brief
**{now}**

No scored candidates available. Pipeline awaiting data ingestion.

---
*Generated by phase3_daily_brief.py*
"""
    else:
        top = candidates[:5]
        top_lines = "\n".join(
            f"- **{c['title'][:100]}** — Score: {c.get('total_score', '?')}/40"
            for c in top
        )

        brief = f"""# Gazzetta di Kyiv — Daily Brief
**{now}**

## Top Narratives
{top_lines}

## Summary
- {len(candidates)} candidates scored
- Top score: {scores.get('top_score', '?')}/40
- Pipeline: phase2 → phase3 → build_site

---
*Generated by phase3_daily_brief.py*
"""

    out_path = os.path.join(DATA, "phase3_daily_brief.md")
    with open(out_path, "w") as f:
        f.write(brief)

    print(json.dumps({"ok": True, "brief_path": out_path, "candidates": len(candidates)}, indent=2))


if __name__ == "__main__":
    main()
